# Variable 'GitHubPat' was defined in the Variables tab
# Variable 'OneLocBuildPat' was defined in the Variables tab
resources:
  repositories:
  - repository: self
    type: git
    ref: dev
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
  - task: OneLocBuild@2
    inputs:
      locProj: 'Localize/LocProject.json'
      outDir: '$(Build.ArtifactStagingDirectory)'
      isCreatePrSelected: true
      repoType: 'gitHub'
      prSourceBranchPrefix: 'locfiles'
      gitHubPatVariable: '$(GitHubPat)'
      gitHubPrMergeMethod: 'squash'
      packageSourceAuth: 'patAuth'
      patVariable: '$(OneLocBuildPat)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...
