codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
coverage:
  status:
    project:
      default:
        target: auto   # require coverage equal or more than current
        if_ci_failed: error #success, failure, error, ignore
        
      # enable different path to sepearate code coverage


comment:
  layout: "reach, diff, flags, files"  

flags: 
  api:
    paths:
      - packages/api/tests
  cli:
    paths:
      - packages/cli/tests
  failpoint-ts:
    paths:
      - packages/failpoint-ts/tests
  fx-core:
    paths:
      - packages/fx-core/tests
  sdk:
    paths:
      - packages/sdk/tests
  server:
    paths:
      - packages/server/tests
  vscode-extension:
    paths:
      - packages/vscode-extension/tests
  manifest:
    paths:
      - packages/manifest/tests