name: Alpha Release

on:
  push:
    tags:
      - 2.0.0-rc.*

jobs:
  azure:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ">=14"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .npmrc file
        run: |
          echo "${{ secrets.NPMRC_CONF }}" > ~/.npmrc

      - name: Build VSIX
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          npm install
          npm run build --if-present
          npm install -g vsce
          vsce package
          ls -alh

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure blob upload
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload --account-name teamsfxpackages --container-name private-preview --file $GITHUB_WORKSPACE/teamsfx-extension-${{ env.RELEASE_VERSION }}.vsix --name teamsfx-extension-${{ env.RELEASE_VERSION }}.vsix