name: Api2teams CD
run-name: Api2teams-${{ github.run_id }}-${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Validate CD branch
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/api2teams' }}
        run: |
          echo It's not allowed to run CD on other branch except api2teams.
          exit 1

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install
        working-directory: packages/api2teams/
        run: |
          npm install

      - name: Package
        working-directory: packages/api2teams/
        run: |
          npm run package

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: publish release to npm org
        working-directory: packages/api2teams/
        run: |
          npm publish --dist-tag alpha