name: issue assigned for app-studio-service 
on:
  issues:
    types: [assigned]
  workflow_dispatch: # allows to run manually for testing
    inputs:
      issueNumber:
        description: 'specific issue number to test issue assigned for app-studio-service action'
        required: true  

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout github action repository
        uses: actions/checkout@v3
        with:
         repository: "microsoft/vscode-github-triage-actions"
         ref: stable 
         path: ./action-base

      - name: Copy action
        run: |
          cp -r .github/actions/issue-assigned-for-app-studio ./action-base/issue-assigned-for-app-studio
          cp -r .github/actions/teamsfx-utils ./action-base/teamsfx-utils
      - name: Npm install
        run: npm install --production --prefix ./action-base
      - name: Build action
        continue-on-error: true
        run: npm run build --prefix ./action-base

      - name: Check assigned issue for app-studio-service
        id: check
        uses: ./action-base/issue-assigned-for-app-studio
        with: 
          token: ${{secrets.GITHUB_TOKEN}}
        env:
          ISSUE_NUMBER: ${{github.event.inputs.issueNumber}}

      - name: Send E-mail to issue assignee
        if: ${{ steps.check.outputs.to != '' }}
        uses: satak/webrequest-action@master
        with:
          url: https://prod-30.eastus.logic.azure.com:443/workflows/9aa865da96054bd89749c2d4ce68df8e/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=uIoB06NUHSnKoZeWjNDI9t4rrhbTBKxJNiBtDoMRSQs
          method: POST
          payload: |
            {
              "to": "${{ steps.check.outputs.to }}",
              "body": "${{ steps.check.outputs.body }}",
              "subject": "${{ steps.check.outputs.subject }}",
              "apiKey": "${{ secrets.MAIL_API_KEY }}"
            }
