name: CD

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha, rc, stable)"
        required: true
        default: "rc"
      skip-version-rc:
        description: "release RC version just with lerna publish, skip run lerna version(yes or no)"
        required: false
        default: "no"
      skip-sync-version-pkg:
        description: "skip sync up target pkg version. input templates to skip sync up version with sdk; fx-core to skip sync up with simpleauth"
        required: false
        default: ""
      pkgs:
        type: string
        required: false
        description: "Please enter the package names you want to publish, such as cli, vscode, sdk, server and template. Please separate multiple entries with spaces"
  schedule:
    - cron: "0 8 * * *"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Validate CD branch
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/hotfix/') && github.ref != 'refs/heads/dev' }}
        run: |
          echo It's not allowed to run CD on other branch except main and dev.
          exit 1

      - name: Validate inputs for main or hotfix
        if: ${{ github.event_name == 'workflow_dispatch' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/')) && github.event.inputs.preid != 'rc' && github.event.inputs.preid != 'stable' }}
        run: |
          echo It's not allowed to release alpha on main branch.
          exit 1

      - name: Valiadte inputs for dev
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev' && github.event.inputs.preid != 'alpha' }}
        run: |
          echo It's not allowed to release RC or stable on dev branch.
          exit 1

      - name: Validate schedule
        if: ${{ github.event_name == 'schedule' && github.ref != 'refs/heads/dev' }}
        run: |
          echo It's not allowed to run schedule release except dev branch.
          exit 1

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CD_PAT }}
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Install wine64
        run: |
          sudo apt update
          sudo apt install wine64 -y

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: manage pkgs to release
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pkgs }}
        run:
          bash .github/scripts/lerna.sh ${{github.event.inputs.pkgs}}

      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'MSFT-yiz'
          git config --global user.email 'yiz@microsoft.com'

      - name: release alpha npm packages to npmjs.org
        if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev' && github.event.inputs.preid == 'alpha')}}
        run: |
          npx lerna version prerelease --preid=alpha.$(git rev-parse --short HEAD) --exact --no-push --allow-branch dev --yes

      - name: version rc npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' && github.ref == 'refs/heads/main' && github.event.inputs.skip-version-rc == 'no'}}
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid=rc --no-changelog --yes
        env:
          SkipSyncup: ${{ github.event.inputs.skip-sync-version-pkg }}

      - name: version rc npm packages to npmjs.org on hotfix
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' && startsWith(github.ref, 'refs/heads/hotfix/') && github.event.inputs.skip-version-rc == 'no'}}
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid=rc-hotfix --no-changelog --allow-branch ${GITHUB_REF#refs/*/} --yes
        env:
          SkipSyncup: ${{ github.event.inputs.skip-sync-version-pkg }}

      - name: version stable npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/')) && github.event.inputs.preid == 'stable' }}
        run: |
          npx lerna version --conventional-commits --conventional-graduate --no-changelog --allow-branch ${GITHUB_REF#refs/*/} --yes
        env:
          SkipSyncup: ${{ github.event.inputs.skip-sync-version-pkg }}

      - name: version change
        id: version-change
        run: |
          echo "::set-output name=CHANGED::$(git tag --points-at HEAD | xargs)"
          echo "::set-output name=TEMPLATE_VERSION::$(git tag --points-at HEAD | grep templates)"
          echo "::set-output name=EXTENSION_VERSION_NUM::$(git tag --points-at HEAD | grep ms-teams-vscode-extension@ | cut -d '@' -f2)"
          echo "::set-output name=EXTENSION_VERSION::$(git tag --points-at HEAD | grep ms-teams-vscode-extension@)"
          echo "::set-output name=SERVER_VERSION_NUM::$(git tag --points-at HEAD | grep @microsoft/teamsfx-server@ | cut -d '@' -f3)"
          echo "::set-output name=SERVER_VERSION::$(git tag --points-at HEAD| grep @microsoft/teamsfx-server@)"
          echo "::set-output name=SIMPLEAUTH_VERSION::$(git tag --points-at HEAD | grep simpleauth)"
          echo "::set-output name=SIMPLEAUTH_VERSION_NUM::$(git tag --points-at HEAD| grep simpleauth| cut -d '@' -f2)"
          if git tag --points-at HEAD | grep templates | grep rc;
          then
              git push -d origin $(git tag --points-at HEAD | grep templates | grep rc)
          fi

      - name: generate templates
        run: |
          .github/scripts/template-zip-autogen.sh ${{ runner.temp }}/teamsfx_templates

      - name: update tag
        uses: richardsimko/update-tag@v1
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'alpha') }}
        with:
          tag_name: "templates-0.0.0-alpha"
        env:
          GITHUB_TOKEN: ${{ secrets.CD_PAT }}

      - name: release templates' alpha version to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'alpha') }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          prerelease: true
          tag: "templates-0.0.0-alpha"
          artifacts: ${{ runner.temp }}/teamsfx_templates/*.zip
          allowUpdates: true

      - name: update tag
        uses: richardsimko/update-tag@v1
        if: ${{ (contains(steps.version-change.outputs.CHANGED, 'templates@') || contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx')) && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        with:
          tag_name: "templates@0.0.0-rc"
        env:
          GITHUB_TOKEN: ${{ secrets.CD_PAT }}

      - name: release templates' RC version to github
        if: ${{ (contains(steps.version-change.outputs.CHANGED, 'templates@') || contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx')) && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          prerelease: true
          tag: "templates@0.0.0-rc"
          artifacts: ${{ runner.temp }}/teamsfx_templates/*.zip
          allowUpdates: true

      - name: Create Templates Stable Release
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          artifacts: ${{ runner.temp }}/teamsfx_templates/*.zip
          name: 'Release for ${{ steps.version-change.outputs.TEMPLATE_VERSION }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version-change.outputs.TEMPLATE_VERSION }}
          allowUpdates: true

      - name: Generate Tag List
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        run: git tag | grep templates > ${{ runner.temp }}/template-tags.txt

      - name: Update Template Tag list Release
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          artifacts: ${{ runner.temp }}/template-tags.txt
          name: 'Template Tag List'
          body: 'Release to maintain template tag list.'
          token: ${{ secrets.github_token }}
          tag: 'template-tag-list'
          allowUpdates: true

      - name: download simpleauth to fx-core
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_on: error
          command: |
            bash ./.github/scripts/download-simpleauth.sh

      - name: publish alpha release to npm org
        if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev' && github.event.inputs.preid == 'alpha')}}
        run: |
          npx lerna publish from-package --dist-tag=alpha --yes --allow-branch dev

      - name: update cli ai key
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.preid == 'stable'||github.event.inputs.preid == 'rc') }}
        uses: jossef/action-set-json-field@v1
        with:
          file: ./packages/cli/package.json
          field: aiKey
          value: ${{ secrets.CLI_PUBLIC_AIKEY }}

      - name: update extension ai key
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.preid == 'stable' || github.event.inputs.preid == 'rc') }}
        uses: jossef/action-set-json-field@v1
        with:
          file: ./packages/vscode-extension/package.json
          field: aiKey
          value: ${{ secrets.EXT_PUBLIC_AIKEY }}

      - name: commit change on local
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.preid == 'stable' || github.event.inputs.preid == 'rc') }}
        run: |
          git add .
          git commit -m "chore: update ai key"

      - name: publish rc npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        run: |
          npx lerna publish from-package --dist-tag=rc --yes

      - name: publish stable npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        run: |
          npx lerna publish from-package --yes

      - name: pack server bits
        if: ${{ contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx-server') }}
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_on: error
          command: |
            sleep 20
            cd ./packages/server
            npm run package

      - name: release daily server bits to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx-server') && github.ref == 'refs/heads/dev'  }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: '@microsoft/teamsfx-server-${{ steps.version-change.outputs.SERVER_VERSION_NUM }}'
          artifacts: ./packages/server/lib/*.exe
          prerelease: true

      - name: release RC server bits to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx-server') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc'}}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: ${{ steps.version-change.outputs.SERVER_VERSION }}
          artifacts: ./packages/server/lib/*.exe
          prerelease: true

      - name: release stable server bits to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx-server') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: ${{ steps.version-change.outputs.SERVER_VERSION }}
          artifacts: ./packages/server/lib/*.exe

      - name: pack vsix
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') }}
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_on: error
          command: |
            sleep 20
            cd ./packages/vscode-extension
            npm install --only=production
            npx vsce package

      - name: release daily VSCode extension to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') && github.ref == 'refs/heads/dev'  }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: 'vscode-extension-${{ steps.version-change.outputs.EXTENSION_VERSION_NUM }}'
          artifacts: ./packages/**/*.vsix
          prerelease: true

      - name: release RC VSCode extension to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc'}}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: ${{ steps.version-change.outputs.EXTENSION_VERSION }}
          artifacts: ./packages/**/*.vsix
          prerelease: true

      - name: release stable VSCode extension to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: ${{ steps.version-change.outputs.EXTENSION_VERSION }}
          artifacts: ./packages/**/*.vsix