name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.os }} node ${{ matrix.node-version }})

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup project
        run: |
          npm run setup

      - name: Lint code
        run: |
          npm run lint

      - name: Unit Test
        run: |
          npx lerna run test:unit --since origin/main

      - name: Integration Test
        run: |
          npx lerna run test:integration --since origin/main

