name: TeamsFx-CICD-Test Triggers 

on:
  workflow_run:
    workflows: ["CD"]
    branches: ["main", "dev"]
    types: ["completed"]

jobs:
  TeamsFxCICDTestTriggers:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger TeamsFx-CICD-Test
        env:
            BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
            curl \
                -u :${{ secrets.GITHUB_TOKEN }} \
                -x POST \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/OfficeDev/TeamsFx-CICD-Test/actions/workflows/trigger_cicd_by_${BRANCH}.yml/dispatches \
                -d "{\"ref\":\"main\"}" 
