name: Code Cleanup Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  missing-header:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
        - fx-core
        - server
        - vscode-extension
        - manifest
        - api
        - cli

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Setup legacy-peer-deps
      run: |
        npm config set legacy-peer-deps true

    - name: Setup project
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: |
          npm run setup

    - name: Install eslint-plugin-header
      run: |
        npm i -d eslint-plugin-header
      working-directory: packages/${{matrix.package}}

    - name: Detect missing header file
      continue-on-error: true
      run: |
        npx eslint --no-eslintrc --plugin header --rule '{"header/header": [2, "../eslint-plugin-teamsfx/config/header.js"]}' --parser-options ecmaVersion:2018 --parser-options sourceType:"module" --parser '@typescript-eslint/parser' --plugin "@typescript-eslint" src/**/*.ts --format unix
      working-directory: packages/${{matrix.package}}


