name: Create Milestone

on: 
  schedule:
    - cron: "20 0 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout github action repository
        uses: actions/checkout@v3
        with:
         repository: "microsoft/vscode-github-triage-actions"
         ref: stable 
         path: ./action-base

      - name: Copy action
        run: cp -r .github/actions/create-milestone ./action-base/create-milestone
      - name: Npm install
        run: npm install --production --prefix ./action-base
      - name: Build action
        run: npm run build --prefix ./action-base

      - name: Run Create Milestone
        uses: ./action-base/create-milestone
        with:
          milestone-prefix: CY
          milestone-days: 14
          advanced-days: 3
          token: ${{secrets.GITHUB_TOKEN}}