name: Daily release

on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  pre-tests:
    name: run e2e test on (${{ matrix.os }} node ${{ matrix.node-version }}) with source code

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: Setup project
        run: |
          npm run setup

      - name: E2E Test
        run: |
          echo "to be enabled."

  daily-release:
    needs: pre-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: Setup project
        run: |
          npm run setup

      - name: release npm packages to npmjs.org
        run: |
          npx lerna publish --canary --yes 

      - name: pack vsix
        working-directory: ./packages/vscode-extension
        run: |
          npm install -g vsce
          npm install --production
          npm run build
          vsce package

      - name: release VSCode extension to github
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            *.vsix

