name: Botbuilder New Version Released
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install npm packages
        run: |
          npm install axios

      - name: Get LTS Version
        id: getLTSVersion
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require("axios");
            const response = await axios.get("https://registry.npmjs.org/botbuilder");
            const ltsVersion = response.data["dist-tags"].latest;
            const ltsVersionTime = response.data.time[ltsVersion];
            const timeDiff = (new Date() - new Date(ltsVersionTime)) / 1000;
            if (timeDiff >= 86400) {
              return 'v' + ltsVersion;
            } else {
              return '';
            }

      - name: Get Release Detail
        if: startsWith(${{steps.getLTSVersion.outputs.result}}, 'v')
        id: detail
        run: |
          responseBody = "<p>Botbuilder ${{steps.getLTSVersion.outputs.result}} has been released.\n Details can be found here: https://github.com/microsoft/botbuilder-js/releases<p>"
          echo "responseBody = $responseBody" >> $GITHUB_OUTPUT

      - name: Setup Email and Recipient
        if: startsWith(${{steps.getLTSVersion.outputs.result}}, 'v')
        id: email
        run: |
          emails="yiqingzhao@microsoft.com"
          subject="Bot Framework JS SDK ${{steps.getLTSVersion.outputs.result}} Released"

          echo "to=$emails" >> $GITHUB_OUTPUT
          echo "subject=$subject" >> $GITHUB_OUTPUT

      - name: Send E-mail Notifications
        if: startsWith(${{steps.getLTSVersion.outputs.result}}, 'v')
        uses: satak/webrequest-action@master
        with:
          url: https://prod-30.eastus.logic.azure.com:443/workflows/9aa865da96054bd89749c2d4ce68df8e/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=uIoB06NUHSnKoZeWjNDI9t4rrhbTBKxJNiBtDoMRSQs
          method: POST
          payload: |
            {
              "to": "${{ steps.email.outputs.to }}",
              "body": ${{ steps.detail.outputs.responseBody }},
              "subject": "${{ steps.email.outputs.subject }}",
              "apiKey": "${{ secrets.MAIL_API_KEY }}"
            }
