name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: packages/simpleauth/

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup .NET
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: 3.1.x
#       - name: use this action, test solution dir
#         uses: zyborg/dotnet-tests-report@v1
#         env:
#           ClientSecret : ${{secrets.FUNCTION_EXTENSION_CLIENT_SECRET}}
#           UnauthorizedAadAppClientSecret : ${{secrets.FUNCTION_EXTENSION_UNAUTHORIZED_AAD_APP_CLIENT_SECRET}}
#           AllowedAppClientSecret : ${{secrets.FUNCTION_EXTENSION_ALLOWED_APP_SECRET}}
#         with:
#           project_path: packages\function-extension\tests\Microsoft.Azure.WebJobs.Extensions.TeamsFx.Tests
#           report_name: my_project_tests
#           report_title: My Project Tests

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install Chrome driver
      run:
        sudo apt-get update && sudo apt-get install -y chromium-chromedriver
    - name: Build
      run: 
        ls && chmod +x "scripts/build.sh" && "scripts/build.sh"
    - name: Test
      env: 
        SimpleAuthAdminClientSecret: ${{secrets.SIMPLE_AUTH_TEST_ADMIN_CLIENT_SECRET}}
        SimpleAuthPassword: ${{secrets.SIMPLE_AUTH_TEST_PASSWORD}}
      run:
        chmod +x "scripts/test.sh" && "scripts/test.sh"
