name: E2E test

on:
  workflow_dispatch:
    inputs:
      cases:
        description: "specific cases to be excuted."
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cases: ${{ steps.list-cases.outputs.cases }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List cases
        id: list-cases
        working-directory: packages/cli
        run: |
          listCases=`find tests/e2e -name "*.tests.ts" -printf "%f\n" | sed 's/.tests.ts//' | jq -R -s -c '[split("\n") | .[]| select(.!="")]'`
          inputCases='${{ github.event.inputs.cases }}'
          cases=`jq --argjson arr1 "$listCases" --argjson arr2 "$inputCases" -n -R -s -c '$arr1 + $arr2'`
          echo "::set-output name=cases::$cases"

  execute-cases:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cases: ${{ fromJson(needs.setup.outputs.cases) }}
    steps:
      - name: echo
        run: |
          echo ${{ matrix.cases }}

  teardown:
    needs: execute-cases
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "tear down"

  report:
    needs: execute-cases
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "report"
