name: E2E test

on:
  schedule:
    - cron: "0 4,7,10 * * *"
  workflow_dispatch:

jobs:
  e2e-tests:
    name: run e2e test on (${{ matrix.os }} node ${{ matrix.node-version }}) with source code
    env:
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      TEST_SUBSCRIPTION_ID: ${{ secrets.TEST_SUBSCRIPTION_ID_2 }}
      TEST_TENANT_ID: ${{ secrets.TEST_TENANT_ID_2 }}
      CI_ENABLED: "true"

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CD_PAT }}
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download Simple Auth bits
        run: |
          $version=Get-Content packages/fx-core/templates/plugins/resource/simpleauth/version.txt
          $tag = "simpleauth@"+$version
          $fileName="Microsoft.TeamsFx.SimpleAuth_$version.zip"
          $url = "https://github.com/OfficeDev/TeamsFx/releases/download/"+$tag+"/"+$fileName
          Invoke-WebRequest $url -OutFile packages/fx-core/templates/plugins/resource/simpleauth/SimpleAuth.zip
        shell: pwsh

      - name: Setup project
        run: |
          npm run setup

      - name: Package CLI
        run: |
          npm run package
          npm pack
          mv *.tgz teamsfx-cli.tgz
          npm install -g teamsfx-cli.tgz
        working-directory: packages/cli

      - name: E2E Test clean
        run: |
          npx lerna run test:e2e:clean

      - name: E2E Test Smoke Cases
        run: |
          npx lerna run test:e2e:smoke

      - name: E2E Test Other Cases
        run: |
          npx lerna run test:e2e:others

      - name: E2E Test Apim Cases
        run: |
          npx lerna run test:e2e:apim
