name: Microsoft Graph Toolkit New Version Released
on:
  repository_dispatch:
    types: [graph-toolkit-released]
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Get Release Detail
        id: detail
        uses: actions/github-script@v6
        with:
          script: |
            const responseBody = "<p>Microsoft Graph Toolkit v" + "${{ github.event.client_payload.version }} has been released.\n Details can be found here: https://github.com/microsoftgraph/microsoft-graph-toolkit/releases/tag/v${{ github.event.client_payload.version }}";
            return responseBody;

      - name: Setup Email and Recipient
        id: email
        run: |
          emails="vsciotadt@microsoft.com;junjieli@microsoft.com;zhshang@microsoft.com;donji@microsoft.com;zhany@microsoft.com"
          subject="Microsoft Graph Toolkit v${{ github.event.client_payload.version }} Released"

          echo "to=$emails" >> $GITHUB_OUTPUT
          echo "subject=$subject" >> $GITHUB_OUTPUT

      - name: Send E-mail Notifications
        run: |
          response=$(curl \
            --request POST \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data "grant_type=client_credentials&client_id=${{ secrets.TEST_CLEAN_CLIENT_ID }}&client_secret=${{ secrets.TEST_CLEAN_CLIENT_SECRET }}&resource=https://management.core.windows.net" \
            "https://login.microsoftonline.com/${{ secrets.TEST_CLEAN_TENANT_ID }}/oauth2/token")
          access_token=`echo $response | jq -r '. | select(.access_token) | .access_token'`
          curl \
            --request POST \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer $access_token" \
            --data '{"to": "${{ steps.email.outputs.to }}", "body": ${{ steps.detail.outputs.result }}, "subject": "${{ steps.email.outputs.subject }}"}' \
            'https://prod-18.northcentralus.logic.azure.com:443/workflows/b33d7861bfc64832a6f62cc8f2213988/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0'
