name: kusto error clustering

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  error-clustering:
    name: run kusto error clustering (self-hosted linux 8cpu node14) 

    runs-on: [self-hosted, linux, 8cpu]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CD_PAT }}
          ref: ${{ github.ref }}
          clean: false

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup project
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_on: error
          command: |
            npm run setup

      - name: Run script kustoErrorClustering.ts
        run: |
          npx ts-node ./.github/scripts/kustoErrorClustering.ts -c
 
