name: kusto error clustering

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  error-clustering:
    name: run kusto error clustering (self-hosted linux 8cpu node14) 

    runs-on: [self-hosted, linux, 8cpu]
    env:
      KUSTO_CLUSTER_NAME: ${{ secrets.KUSTO_CLUSTER_NAME }}
      KUSTO_AAD_APP_ID: ${{ secrets.KUSTO_AAD_APP_ID }}
      KUSTO_AAD_APP_KEY: ${{ secrets.KUSTO_AAD_APP_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CD_PAT }}
          ref: ${{ github.ref }}
          clean: false

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: npm install
        run: |
          npm install

      - name: Run script kustoErrorClustering.ts
        run: |
          npx ts-node ./.github/scripts/kustoErrorClustering.ts -c
 
