name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-format:
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'edited' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup Project
        run: |
          npm run setup

      - name: prettier check files in PR
        run: |
          VAR=$(realpath .github/scripts/lint-pr.sh)
          npx lerna exec -- bash $VAR ${{ github.event.pull_request.base.ref }}

      - name: Check if there are changes
        id: changes
        run: |
          git add .
          VAR=$(git diff --cached --name-only)
          if [ ! -z "$VAR" ]
          then 
            echo "there has some prettier format error, you may run npm run setup local, and check your commit files is formatted."
            exit 1
          fi