name: milestoned-azdo

on: 
  issues:
    types: [milestoned]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout github action repository
        uses: actions/checkout@v3
        with:
         repository: "microsoft/vscode-github-triage-actions"
         ref: stable 
         path: ./action-base
      
      - name: Copy action
        run: cp -r .github/actions/milestoned ./action-base/milestoned
      - name: Npm install
        run: npm install --production --prefix ./action-base
      - name: Build action
        continue-on-error: true
        run: npm run build --prefix ./action-base

      - name: Create AZDO Item 
        uses: ./action-base/milestoned
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          milestone-prefix: "CY"
          devops-token: ${{secrets.ADO_PAT}}
          devops-org: "msazure"
          devops-projectId: "Microsoft Teams Extensibility"
          title-prefix: "[Github]"
          bug-label: "bug"
          bug-area-path: "Microsoft Teams Extensibility"
          bug-iteration-path: "Microsoft Teams Extensibility"