name: SDK CI

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/sdk/**

jobs:
  build-and-test-on-latest-version:
    name: Test SDK on (${{ matrix.os }} with node ${{ matrix.node-version }})

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup project
        run: |
          npm run setup

      - name: Remove package-lock(Windows)
        if: matrix.os == 'windows-latest'
        uses: JesseTG/rm@v1.0.0
        with:
          path: packages\sdk\package-lock.json

      - name: Remove package-lock(Linux)
        if: matrix.os != 'windows-latest'
        run: |
          rm packages/sdk/package-lock.json

      - name: Setup project
        run: |
          npm run bootstrap

      - name: Unit Test
        run: |
          npm run test:unit
        working-directory: ./packages/sdk

      - name: Integration Test
        env:
          SDK_INTEGRATION_SQL_ENDPOINT: ${{secrets.SDK_INTEGRATIONTEST_SQL_ENDPOINT}}
          SDK_INTEGRATION_SQL_DATABASE_NAME: ${{secrets.SDK_INTEGRATIONTEST_SQL_DATABASE}}
          SDK_INTEGRATION_SQL_USER_NAME: ${{secrets.SDK_INTEGRATIONTEST_SQL_USERNAME}}
          SDK_INTEGRATION_SQL_PASSWORD: ${{secrets.SDK_INTEGRATIONTEST_SQL_PASSWORD}}
          SDK_INTEGRATION_RESOURCE_GROUP_NAME: ${{secrets.SDK_INTEGRATIONTEST_GROUP_NAME}}
          SDK_INTEGRATION_TEST_ACCOUNT_SUBSCRIPTION_ID: ${{secrets.SDK_INTEGRATIONTEST_SUBSCRIPTION_ID}}
          SDK_INTEGRATION_TEST_ACCOUNT_NAME: ${{secrets.SDK_INTEGRATIONTEST_TEST_USERNAME}}
          SDK_INTEGRATION_TEST_ACCOUNT_PASSWORD: ${{secrets.SDK_INTEGRATIONTEST_TEST_PASSWORD}}
        run: |
          npm run test:integration
        working-directory: ./packages/sdk
