name: SDK CI

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/sdk/**

jobs:
  build-and-test-on-latest-version:
    name: Test SDK on (${{ matrix.os }} with node ${{ matrix.node-version }})

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup project
        run: |
          npm run setup

      - name: Remove package-lock(Windows)
        if: matrix.os == 'windows-latest'
        uses: JesseTG/rm@v1.0.0
        with:
          path: packages\sdk\package-lock.json

      - name: Remove package-lock(Linux)
        if: matrix.os != 'windows-latest'
        run: |
          rm packages/sdk/package-lock.json
      
      - name: Setup project
        run: |
          npm run bootstrap

      - name: Test
        run: |
          npm run test:unit
        working-directory: ./packages/sdk