name: SimpleAuth CI

on:
  push:
    paths:
      - "packages/simpleauth/**"
    branches: [main]
  pull_request:
    paths:
      - "packages/simpleauth/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/simpleauth/

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Build
        run: dotnet build -c Release -p:WebDriverPlatform=linux64 Microsoft.TeamsFx.SimpleAuth.sln
      - name: setup env
        env:
          creds: ${{ secrets.AZURE_TEST_CREDENTIALS }}
        run: |
          bash setup-testing-env.sh simpleauth $GITHUB_ENV
        working-directory: .github/scripts
      - name: Test
        run: chmod +x "scripts/test.sh" && "scripts/test.sh"
