name: Spec-Parser CD
run-name: Spec-Parser-${{ github.run_id }}-${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/spec-parser' }}
        run: |
          echo It's not allowed to run CD on other branch except spec-parser.
          exit 1