name: Teams JS SDK New Version Released
on:
  repository_dispatch:
    types: [teamsjs-released]
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Detail
        run: |
          release=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/OfficeDev/microsoft-teams-library-js/releases/tags/v${{ github.event.client_payload.version }})
          body=$(echo $release | jq ".body")
          echo $body

      - name: Test
        id: test
        working-directory: packages/cli
        run: |
          emails="yiqingzhao@microsoft.com"

          subject="Teams-JS v${{ github.event.client_payload.version }} Released"

          echo "::set-output name=body::$body"
          echo "::set-output name=to::$emails"
          echo "::set-output name=subject::$subject"


      - name: Send E-mail Notifications
        uses: satak/webrequest-action@master
        with:
          url: https://prod-30.eastus.logic.azure.com:443/workflows/9aa865da96054bd89749c2d4ce68df8e/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=uIoB06NUHSnKoZeWjNDI9t4rrhbTBKxJNiBtDoMRSQs
          method: POST
          payload: |
            {
              "to": "${{ steps.test.outputs.to }}",
              "body": "${{ steps.test.outputs.body }}",
              "subject": "${{ steps.test.outputs.subject }}",
              "apiKey": "${{ secrets.MAIL_API_KEY }}"
            }

