name: TEST

on:
  push:
    branches: ["qidon/sideloading"]
  pull_request:
    branches: ["qidon/sideloading"]
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'qidon'
          git config --global user.email 'qidon@qidon.onmicrosoft.com'

      - name: replace sideloading placeholders
        run: bash .github/scripts/sideloading-replace.sh
        env:
          SIDELOADING_SERVICE_ENDPOINT: ${{ secrets.SIDELOADING_SERVICE_ENDPOINT }}
          SIDELOADING_SERVICE_SCOPE: ${{ secrets.SIDELOADING_SERVICE_SCOPE }}

      - name: commit change on local
        run: |
          git add .
          git commit -m "chore: replace sideloading placeholders"

      - name: pack cli
        run: |
          cd packages/cli/
          npm pack

      - name: upload release info to artifact
        uses: actions/upload-artifact@v3
        with:
          name: clizip
          path: |
            packages/cli/*.tgz
