name: uitest

on:
  workflow_dispatch:
    inputs:
      target-vsix-run-id:
        description: "target vsix github action run id"
        required: true
        type: string

      target-cli-version:
        description: "target cli version or tag, like latest, beta or alpha"
        required: true
        type: string

      target-sample-ref:
        description: "target sample ref, like v1.1.0, v2.0.0 or dev"
        required: false
        type: string
        default: dev

      test-case:
        description: 'test case, e.g. ["localdebug-tab", "localdebug-bot"], Set empty to run all predefined cases'
        required: false
        type: string

      os:
        default: '["macos-latest", "ubuntu-latest", "windows-latest"]'
        description: 'os, e.g. ["macos-latest", "ubuntu-latest", "windows-latest"]'
        required: false
        type: string

      node-version:
        default: "[16]"
        description: "node version, e.g. [16]"
        required: false
        type: string

      email-receiver:
        description: "email notification receiver"
        required: false
        type: string

      source-testplan-id:
        description: "source testplan id: 24569079."
        required: false
        type: string
        default: "24569079"

      target-testplan-name:
          description: "For example: CY230919. Sync test result to this test plan."
          required: false
          type: string
  schedule:
    - cron: "0 18 * * *"

permissions:
  actions: read

jobs:
  setup-uitest:
    runs-on: ubuntu-latest
    environment: engineering
    permissions:
      id-token: write
      contents: read
    env:
      AUTO_TEST_PLAN_ID: ${{ github.event.inputs.source-testplan-id }}
      TARGET_TEST_PLAN_NAME: ${{ github.event.inputs.target-testplan-name }}
      DEVTUNNEL_CLIENT_ID: ${{ secrets.TEST_CLEAN_CLIENT_ID }}
      DEVTUNNEL_CLIENT_SECRET: ${{ secrets.TEST_CLEAN_CLIENT_SECRET }}
      DEVTUNNEL_TENANT_ID: ${{ secrets.TEST_CLEAN_TENANT_ID }}

    steps:
      - name: clean devtunnel
        env:
          REGION_NAME: ''
        run: |
          wget https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1249+67b1cd300c/linux-x64-devtunnel -O ./devtunnel
          chmod 777 ./devtunnel
          ./devtunnel user login --sp-tenant-id ${{env.DEVTUNNEL_TENANT_ID}} --sp-client-id ${{env.DEVTUNNEL_CLIENT_ID}} --sp-secret ${{env.DEVTUNNEL_CLIENT_SECRET}}
          ./devtunnel delete-all -f