name: publish to VSCode marketplace
run-name: Publish-${{ inputs.run_id }}-${{ github.ref_name }}-isPreview-${{ inputs.isPreview }}
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Input the CD pipeline run ID to fetch the artifact"
        required: true
        default: ""
      isPreview:
        description: "Publish VSIX as a preview version(yes or no)"
        required: true
        default: "no"

jobs:
  publish-to-vscode-marketplace:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install VSCE command
        run: |
          npm install vsce -g

      - name: Download release artifacts
        uses: Legit-Labs/action-download-artifact@v2
        with:
          run_id: ${{ github.event.inputs.run_id }}
          name: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: cd.yml
          path: .
      
      - name: Get prerelease tag name
        if: ${{ github.event.inputs.isPreview != 'no' }}
        id: prerelease-tag
        run: |
          tagName=$(jq -r '.[]|select(.name=="ms-teams-vscode-extension")| .name+"-"+.version' versions.json)
          echo "===================== TagName=$tagName"
          echo "tagName=$tagName" >> $GITHUB_OUTPUT

      - name: release preview
        if: ${{ github.event.inputs.isPreview != 'no' }}
        env:
          PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish --pre-release --pat $PAT --packagePath *.vsix
      
      - if: ${{ github.event.inputs.isPreview != 'no' }}
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ steps.prerelease-tag.outputs.tagName }}
          
      - name: release to VSCode marketplace
        if: ${{ github.event.inputs.isPreview == 'no' }}
        run: vsce publish --pat $PAT --packagePath *.vsix
        env:
          PAT: ${{ secrets.VSCE_PAT }}
